# Generated by Django 5.2.4 on 2025-08-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'muster',
            },
        ),
    ]
